
package Vistas;

import Conexion.conectar;
import FiveCodMover.FiveCodMoverJFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import javax.swing.*;
import java.net.URI;
import java.util.prefs.Preferences;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Image;
import java.awt.Toolkit;



public class d_general extends javax.swing.JFrame {

  
    
    
    
    public d_general() {
        initComponents();
        Tablageneral.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
        setIconImage(getIconImage());
        mostrardatos("");
        Limpiar();
        centrar_datos();
        setLocationRelativeTo(null);
       
        
    }
    
    
  //validar para que no acepte duplicados
    public void EvitarDuplicado(){
                
                
                DefaultTableModel modelo=new DefaultTableModel(){
            
            
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                if(columnas>=0)
                {
                    return false;
                    
                }else{
                    return true;
                }
                  
            }
    
    
    
    };
            
                for (int i = 0; i < Tablageneral.getRowCount() ; i++) { //recorrido por todas las filas de la tabla
                    if(Tablageneral.getValueAt(i, 0).equals(txtNRegistro.getText())) // verificar si el producto esta registrado
                    {
                    JOptionPane.showMessageDialog(null, "Ya existe alguien con este numero de registro");
                    modelo.removeRow(i); //eliminar la fila que se va a repetir
                    
                    }   
                        
                }
            
            
            }
       

    
  public void centrar_datos(){ //metodo centrar alineación centrada en celdas
  
DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
tcr.setHorizontalAlignment(SwingConstants.CENTER);



Tablageneral.getColumnModel().getColumn(0).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(1).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(3).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(4).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(5).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(6).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(7).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(8).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(9).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(10).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(11).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(12).setCellRenderer(tcr);
Tablageneral.getColumnModel().getColumn(13).setCellRenderer(tcr);

 
  }          
            

   @Override
    public Image getIconImage() {    
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Img/I7C.png"));
    return retValue;
    }


  
  
  
  
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    
    public void mostrardatos(String valor){
        
        conectar cc=new conectar();
        Connection cn=cc.conexion();
        
        
        

        DefaultTableModel modelo=new DefaultTableModel(){
           
            
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                if(columnas>=0)
                {
                    return false;
                    
                }else{
                    return true;
                }
                  
            }
    
             
    
    };
       
        
        
        modelo.addColumn("Numero de registro");
        modelo.addColumn("Numero de medidor");
        modelo.addColumn("Usuario");
        modelo.addColumn("Dirección");
        modelo.addColumn("2014");
        modelo.addColumn("2015");
        modelo.addColumn("2016");
        modelo.addColumn("2017");
        modelo.addColumn("2018");
        modelo.addColumn("2019");
        modelo.addColumn("2020");
        modelo.addColumn("2021");
        modelo.addColumn("2022");
        modelo.addColumn("2023");        
        
        
        Tablageneral.setModel(modelo); 
            
     
     
    Tablageneral.getColumnModel().getColumn(0).setPreferredWidth(120); 
    Tablageneral.getColumnModel().getColumn(0).setMinWidth(120); 
    Tablageneral.getColumnModel().getColumn(0).setMaxWidth(120); 
    
    Tablageneral.getColumnModel().getColumn(1).setPreferredWidth(125);
    Tablageneral.getColumnModel().getColumn(1).setMinWidth(125); 
    Tablageneral.getColumnModel().getColumn(1).setMaxWidth(125); 
   
     Tablageneral.getColumnModel().getColumn(2).setPreferredWidth(250);
    Tablageneral.getColumnModel().getColumn(2).setMinWidth(250); 
    Tablageneral.getColumnModel().getColumn(2).setMaxWidth(250); 
    
    Tablageneral.getColumnModel().getColumn(3).setPreferredWidth(250);
    Tablageneral.getColumnModel().getColumn(3).setMinWidth(250); 
    Tablageneral.getColumnModel().getColumn(3).setMaxWidth(250); 
    
    Tablageneral.getColumnModel().getColumn(4).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(4).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(4).setMaxWidth(40); 
    
    Tablageneral.getColumnModel().getColumn(5).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(5).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(5).setMaxWidth(40); 
    
    Tablageneral.getColumnModel().getColumn(6).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(6).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(6).setMaxWidth(40); 
    
    Tablageneral.getColumnModel().getColumn(7).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(7).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(7).setMaxWidth(40); 
    
    Tablageneral.getColumnModel().getColumn(8).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(8).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(8).setMaxWidth(40); 
    
    Tablageneral.getColumnModel().getColumn(9).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(9).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(9).setMaxWidth(40); 
    
    Tablageneral.getColumnModel().getColumn(10).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(10).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(10).setMaxWidth(40);
    
    Tablageneral.getColumnModel().getColumn(11).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(11).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(11).setMaxWidth(40); 
    
    Tablageneral.getColumnModel().getColumn(12).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(12).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(12).setMaxWidth(40); 
    
    Tablageneral.getColumnModel().getColumn(13).setPreferredWidth(40);
    Tablageneral.getColumnModel().getColumn(13).setMinWidth(40); 
    Tablageneral.getColumnModel().getColumn(13).setMaxWidth(40); 
    
    
        
        
        
        
        String sql="";
        
        if (valor.equals(""))
        {
            sql="SELECT * FROM deudasgeneral";
        }
        else{
            sql="SELECT * FROM deudasgeneral WHERE id_NRegistro LIKE '%"+valor+"%' OR nmedidor LIKE '%"+valor+"%' OR apellidosynombres LIKE '%"+valor+"%' OR direccion LIKE '%"+valor+"%' OR d_2014 LIKE '%"+valor+"%' OR d_2015 LIKE '%"+valor+"%' OR d_2016 LIKE '%"+valor+"%' OR d_2017 LIKE '%"+valor+"%' OR d_2018 LIKE '%"+valor+"%' OR d_2019 LIKE '%"+valor+"%' OR d_2020 LIKE '%"+valor+"%' OR d_2021 LIKE '%"+valor+"%' OR d_2022 LIKE '%"+valor+"%' OR d_2023 LIKE '%"+valor+"%'";
        }  
        
        
        
        
        String []datos=new String [14];
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            datos[6]=rs.getString(7);
            datos[7]=rs.getString(8);
            datos[8]=rs.getString(9);
            datos[9]=rs.getString(10);
            datos[10]=rs.getString(11);
            datos[11]=rs.getString(12);
            datos[12]=rs.getString(13);
            datos[13]=rs.getString(14);
           
            modelo.addRow(datos);
            
            }
           
                     
//            TablaGeneral.setModel(modelo);
        }catch(SQLException ex){
            Logger.getLogger(d_general.datos.class.getName()).log(Level.SEVERE,null,ex);
        }
        
       
        
        
        
        
    }
    
   
        
    
    
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        PopupMenu = new javax.swing.JPopupMenu();
        MenuItemModificar = new javax.swing.JMenuItem();
        MenuItemEliminar = new javax.swing.JMenuItem();
        panel = new javax.swing.JPanel();
        txtNMedidor = new LIB.JTexfieldPH_FielTex();
        txtNRegistro = new LIB.JTexfieldPH_FielTex();
        txtayn = new LIB.JTexfieldPH_FielTex();
        txtd_2014 = new LIB.JTexfieldPH_FielTex();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablageneral = new javax.swing.JTable();
        DTech = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtActualizar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtdireccion = new LIB.JTexfieldPH_FielTex();
        txtd_2015 = new LIB.JTexfieldPH_FielTex();
        txtd_2016 = new LIB.JTexfieldPH_FielTex();
        txtd_2017 = new LIB.JTexfieldPH_FielTex();
        txtd_2018 = new LIB.JTexfieldPH_FielTex();
        txtd_2019 = new LIB.JTexfieldPH_FielTex();
        txtd_2020 = new LIB.JTexfieldPH_FielTex();
        txtd_2021 = new LIB.JTexfieldPH_FielTex();
        txtd_2022 = new LIB.JTexfieldPH_FielTex();
        txtd_2023 = new LIB.JTexfieldPH_FielTex();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        MenuSalirDispose = new javax.swing.JMenuItem();
        MenuSalirExit = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu24 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MILimpiar = new javax.swing.JMenuItem();
        MIMostrar = new javax.swing.JMenuItem();
        MIRegresar = new javax.swing.JMenuItem();
        MINuevoprincipal = new javax.swing.JMenuItem();

        MenuItemModificar.setText("Modificar");
        MenuItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemModificarActionPerformed(evt);
            }
        });
        PopupMenu.add(MenuItemModificar);

        MenuItemEliminar.setText("Eliminar");
        MenuItemEliminar.setComponentPopupMenu(PopupMenu);
        MenuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminarActionPerformed(evt);
            }
        });
        PopupMenu.add(MenuItemEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));
        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNMedidor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNMedidor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtNMedidor.setOpaque(false);
        txtNMedidor.setPlaceholder("Nro de medidor");
        txtNMedidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNMedidorActionPerformed(evt);
            }
        });
        panel.add(txtNMedidor, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 240, 40));

        txtNRegistro.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNRegistro.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtNRegistro.setOpaque(false);
        txtNRegistro.setPlaceholder("Nro de registro");
        txtNRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNRegistroActionPerformed(evt);
            }
        });
        panel.add(txtNRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 240, 40));

        txtayn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtayn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtayn.setOpaque(false);
        txtayn.setPlaceholder("Apellidos y Nombres");
        txtayn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaynActionPerformed(evt);
            }
        });
        panel.add(txtayn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 40));

        txtd_2014.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2014.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2014.setOpaque(false);
        txtd_2014.setPlaceholder("deuda 2014");
        txtd_2014.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2014ActionPerformed(evt);
            }
        });
        panel.add(txtd_2014, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 150, 40));

        Tablageneral.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tablageneral.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Tablageneral.setComponentPopupMenu(PopupMenu);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Tablageneral, org.jdesktop.beansbinding.ELProperty.create("${editingRow}"), Tablageneral, org.jdesktop.beansbinding.BeanProperty.create("autoscrolls"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(Tablageneral);

        panel.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 1160, 224));

        DTech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DTECHINNOVA1.3.png"))); // NOI18N
        DTech.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DTech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DTechMouseClicked(evt);
            }
        });
        panel.add(DTech, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 30, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CREADOPOR1.png"))); // NOI18N
        panel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, -1, -1));

        btnBuscar.setBackground(new java.awt.Color(10, 144, 203));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setMaximumSize(new java.awt.Dimension(103, 31));
        btnBuscar.setMinimumSize(new java.awt.Dimension(103, 31));
        btnBuscar.setPreferredSize(new java.awt.Dimension(103, 31));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        panel.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 110, 40));

        txtActualizar.setBackground(new java.awt.Color(10, 144, 203));
        txtActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        txtActualizar.setForeground(new java.awt.Color(255, 255, 255));
        txtActualizar.setText("Actualizar datos");
        txtActualizar.setMaximumSize(new java.awt.Dimension(103, 31));
        txtActualizar.setMinimumSize(new java.awt.Dimension(103, 31));
        txtActualizar.setPreferredSize(new java.awt.Dimension(103, 31));
        txtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActualizarActionPerformed(evt);
            }
        });
        panel.add(txtActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 160, 50));

        btnAgregar.setBackground(new java.awt.Color(10, 144, 203));
        btnAgregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar registro");
        btnAgregar.setMaximumSize(new java.awt.Dimension(103, 31));
        btnAgregar.setMinimumSize(new java.awt.Dimension(103, 31));
        btnAgregar.setPreferredSize(new java.awt.Dimension(103, 31));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        panel.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 160, 50));

        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });
        panel.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 580, 230, 40));

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 34)); // NOI18N
        jLabel1.setText("GENERAL");
        panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, 200, 70));

        txtdireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtdireccion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtdireccion.setOpaque(false);
        txtdireccion.setPlaceholder("Dirección");
        txtdireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdireccionActionPerformed(evt);
            }
        });
        panel.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 240, 40));

        txtd_2015.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2015.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2015.setOpaque(false);
        txtd_2015.setPlaceholder("deuda 2015");
        txtd_2015.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2015ActionPerformed(evt);
            }
        });
        panel.add(txtd_2015, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 150, 40));

        txtd_2016.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2016.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2016.setOpaque(false);
        txtd_2016.setPlaceholder("deuda 2016");
        txtd_2016.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2016ActionPerformed(evt);
            }
        });
        panel.add(txtd_2016, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 150, 40));

        txtd_2017.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2017.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2017.setOpaque(false);
        txtd_2017.setPlaceholder("deuda 2017");
        txtd_2017.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2017ActionPerformed(evt);
            }
        });
        panel.add(txtd_2017, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 230, 150, 40));

        txtd_2018.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2018.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2018.setOpaque(false);
        txtd_2018.setPlaceholder("deuda 2018");
        txtd_2018.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2018ActionPerformed(evt);
            }
        });
        panel.add(txtd_2018, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 80, 150, 40));

        txtd_2019.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2019.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2019.setOpaque(false);
        txtd_2019.setPlaceholder("deuda 2019");
        txtd_2019.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2019ActionPerformed(evt);
            }
        });
        panel.add(txtd_2019, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 130, 150, 40));

        txtd_2020.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2020.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2020.setOpaque(false);
        txtd_2020.setPlaceholder("deuda 2020");
        txtd_2020.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2020ActionPerformed(evt);
            }
        });
        panel.add(txtd_2020, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 180, 150, 40));

        txtd_2021.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2021.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2021.setOpaque(false);
        txtd_2021.setPlaceholder("deuda 2021");
        txtd_2021.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2021ActionPerformed(evt);
            }
        });
        panel.add(txtd_2021, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 150, 40));

        txtd_2022.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2022.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2022.setOpaque(false);
        txtd_2022.setPlaceholder("deuda 2022");
        txtd_2022.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2022ActionPerformed(evt);
            }
        });
        panel.add(txtd_2022, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 80, 150, 40));

        txtd_2023.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtd_2023.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtd_2023.setOpaque(false);
        txtd_2023.setPlaceholder("deuda 2023");
        txtd_2023.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtd_2023ActionPerformed(evt);
            }
        });
        panel.add(txtd_2023, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 130, 150, 40));

        MenuArchivo.setText("Archivo");
        MenuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArchivoActionPerformed(evt);
            }
        });

        jMenu1.setText("Salir");

        MenuSalirDispose.setText("Salir de esta ventana");
        MenuSalirDispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirDisposeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSalirDispose);

        MenuSalirExit.setText("Salir del programa");
        MenuSalirExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirExitActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSalirExit);

        MenuArchivo.add(jMenu1);

        jMenuItem19.setText("Actualizar Ventana");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        MenuArchivo.add(jMenuItem19);

        jMenuBar1.add(MenuArchivo);

        jMenu14.setText("Deudas");

        jMenu15.setText("2014");

        jMenuItem22.setText("Abrir");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem22);

        jMenuItem23.setText("Abrir en una nueva ventana");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem23);

        jMenu14.add(jMenu15);

        jMenu16.setText("2015");

        jMenuItem24.setText("Abrir");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem24);

        jMenuItem25.setText("Abrir en una nueva ventana");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem25);

        jMenu14.add(jMenu16);

        jMenu17.setText("2016");

        jMenuItem26.setText("Abrir");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem26);

        jMenuItem27.setText("Abrir en una nueva ventana");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem27);

        jMenu14.add(jMenu17);

        jMenu18.setText("2017");

        jMenuItem28.setText("Abrir");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu18.add(jMenuItem28);

        jMenuItem29.setText("Abrir en una nueva ventana");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu18.add(jMenuItem29);

        jMenu14.add(jMenu18);

        jMenu19.setText("2018");

        jMenuItem30.setText("Abrir");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem30);

        jMenuItem31.setText("Abrir en una nueva ventana");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem31);

        jMenu14.add(jMenu19);

        jMenu20.setText("2019");

        jMenuItem32.setText("Abrir");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem32);

        jMenuItem33.setText("Abrir en una nueva ventana");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem33);

        jMenu14.add(jMenu20);

        jMenu21.setText("2020");

        jMenuItem34.setText("Abrir");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem34);

        jMenuItem35.setText("Abrir en una nueva ventana");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem35);

        jMenu14.add(jMenu21);

        jMenu22.setText("2021");

        jMenuItem36.setText("Abrir");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem36);

        jMenuItem37.setText("Abrir en una nueva ventana");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem37);

        jMenu14.add(jMenu22);

        jMenu23.setText("2022");

        jMenuItem38.setText("Abrir");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem38);

        jMenuItem39.setText("Abrir en una nueva ventana");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem39);

        jMenu14.add(jMenu23);

        jMenu24.setText("2023");

        jMenuItem40.setText("Abrir");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu24.add(jMenuItem40);

        jMenuItem41.setText("Abrir en una nueva ventana");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu24.add(jMenuItem41);

        jMenu14.add(jMenu24);

        jMenuBar1.add(jMenu14);

        jMenu2.setText("Opciones");

        MILimpiar.setText("Limpiar celdas");
        MILimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MILimpiarActionPerformed(evt);
            }
        });
        jMenu2.add(MILimpiar);

        MIMostrar.setText("Mostrar todos los registros");
        MIMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIMostrarActionPerformed(evt);
            }
        });
        jMenu2.add(MIMostrar);

        MIRegresar.setText("Regresar a la ventana principal");
        MIRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIRegresarActionPerformed(evt);
            }
        });
        jMenu2.add(MIRegresar);

        MINuevoprincipal.setText("Abrir la ventana principal en una nueva ventana");
        MINuevoprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINuevoprincipalActionPerformed(evt);
            }
        });
        jMenu2.add(MINuevoprincipal);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 1173, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        bindingGroup.bind();

        setSize(new java.awt.Dimension(1189, 690));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
 
    String id_deudageneral= "";
    private void MenuItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemModificarActionPerformed
       
        
    int fila=Tablageneral.getSelectedRow();
    
    if(fila>=0){
        
    txtNRegistro.setText(Tablageneral.getValueAt(fila,0).toString());
    txtNMedidor.setText(Tablageneral.getValueAt(fila,1).toString());
    txtayn.setText(Tablageneral.getValueAt(fila,2).toString());
    txtdireccion.setText(Tablageneral.getValueAt(fila,3).toString());
    
    txtd_2014.setText(Tablageneral.getValueAt(fila,4).toString());
    txtd_2015.setText(Tablageneral.getValueAt(fila,5).toString());
    txtd_2016.setText(Tablageneral.getValueAt(fila,6).toString());
    txtd_2017.setText(Tablageneral.getValueAt(fila,7).toString());
    txtd_2018.setText(Tablageneral.getValueAt(fila,8).toString());
    txtd_2019.setText(Tablageneral.getValueAt(fila,9).toString());
    txtd_2020.setText(Tablageneral.getValueAt(fila,10).toString());
    txtd_2021.setText(Tablageneral.getValueAt(fila,11).toString());
    txtd_2022.setText(Tablageneral.getValueAt(fila,12).toString());
    txtd_2023.setText(Tablageneral.getValueAt(fila,13).toString());
    
    

    }
    else{
        JOptionPane.showMessageDialog(null,"No se encontro fila");
    }
     
        
        
        
        
    }//GEN-LAST:event_MenuItemModificarActionPerformed

    private void MILimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MILimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_MILimpiarActionPerformed

    private void MIMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIMostrarActionPerformed
       mostrardatos("");
       centrar_datos();
    }//GEN-LAST:event_MIMostrarActionPerformed

    private void MIRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegresarActionPerformed
      d_general ss = new d_general();
        ss.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_MIRegresarActionPerformed

    private void MINuevoprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINuevoprincipalActionPerformed
         d_general ss = new d_general();
         ss.setVisible(true);           
    }//GEN-LAST:event_MINuevoprincipalActionPerformed

    private void MenuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuArchivoActionPerformed

    private void MenuSalirDisposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirDisposeActionPerformed
        dispose(); 
    }//GEN-LAST:event_MenuSalirDisposeActionPerformed

    private void MenuSalirExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSalirExitActionPerformed

    private void MenuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminarActionPerformed
        
        
int q1 = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar este registro?","Mensaje",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
if (q1 == 0){
conectar cc=new conectar();
        Connection cn=cc.conexion();
        int fila=Tablageneral.getSelectedRow();
        String cod="";
        cod=Tablageneral.getValueAt(fila,0).toString();
        try{
            PreparedStatement pst=cn.prepareStatement("DELETE FROM deudasgeneral WHERE id_NRegistro='"+cod+"'");
            pst.executeUpdate();
            mostrardatos("");
            centrar_datos();
        } catch (Exception e){
        }  
}
if (q1 == 1){

}

        
        
        
        
        
        
        
    }//GEN-LAST:event_MenuItemEliminarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed

        conectar cc=new conectar();
        Connection cn=cc.conexion();
        EvitarDuplicado();
        try{
            PreparedStatement pst=cn.prepareStatement("INSERT INTO deudasgeneral (id_NRegistro,nmedidor,apellidosynombres,direccion,d_2014,d_2015,d_2016,d_2017,d_2018,d_2019,d_2020,d_2021,d_2022,d_2023) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,txtNRegistro.getText());
            pst.setString(2,txtNMedidor.getText());
            pst.setString(3,txtayn.getText());
            pst.setString(4,txtdireccion.getText());
            pst.setString(5,txtd_2014.getText());
            pst.setString(6,txtd_2015.getText());
            pst.setString(7,txtd_2016.getText());
            pst.setString(8,txtd_2017.getText());
            pst.setString(9,txtd_2018.getText());
            pst.setString(10,txtd_2019.getText());
            pst.setString(11,txtd_2020.getText());
            pst.setString(12,txtd_2021.getText());
            pst.setString(13,txtd_2022.getText());
            pst.setString(14,txtd_2023.getText());
           

            int a=pst.executeUpdate();

            if(a>0){
                JOptionPane.showMessageDialog(null,"Registro exitoso");
                mostrardatos("");
                centrar_datos();
            }
            else{
                JOptionPane.showMessageDialog(null,"Error al agregar");
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarActionPerformed

        conectar cc=new conectar();
        Connection cn=cc.conexion();

        try{

            PreparedStatement pst=cn.prepareStatement("UPDATE deudasgeneral SET d_2023='"+txtd_2023.getText()+"',d_2022='"+txtd_2022.getText()+"',d_2021='"+txtd_2021.getText()+"',d_2020='"+txtd_2020.getText()+"',d_2019='"+txtd_2019.getText()+"',d_2018='"+txtd_2018.getText()+"',d_2017='"+txtd_2017.getText()+"',d_2016='"+txtd_2016.getText()+"',d_2015='"+txtd_2015.getText()+"',d_2014='"+txtd_2014.getText()+"',direccion='"+txtdireccion.getText()+"',apellidosynombres='"+txtayn.getText()+"',nmedidor='"+txtNMedidor.getText()+"',id_NRegistro ='"+txtNRegistro.getText()+"' WHERE id_NRegistro='"+id_deudageneral+"' ");
            id_deudageneral=txtNRegistro.getText();
            pst.executeUpdate();
            mostrardatos("");
            centrar_datos();
            JOptionPane.showMessageDialog(null, "Información Actualizada");
        }catch(Exception e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_txtActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrardatos(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void DTechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTechMouseClicked
        try {
            if(Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if(desktop.isSupported(Desktop.Action.BROWSE)){

                    desktop.browse(new URI ("https://wa.me/+51928583538?text=Hola.%20Necesito%20de%20su%20servicio."));

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DTechMouseClicked

    private void txtd_2014ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2014ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2014ActionPerformed

    private void txtaynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaynActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaynActionPerformed

    private void txtNRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNRegistroActionPerformed

    private void txtNMedidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNMedidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNMedidorActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        mostrardatos("");
        centrar_datos();
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void txtdireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdireccionActionPerformed

    private void txtd_2015ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2015ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2015ActionPerformed

    private void txtd_2016ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2016ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2016ActionPerformed

    private void txtd_2017ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2017ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2017ActionPerformed

    private void txtd_2018ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2018ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2018ActionPerformed

    private void txtd_2019ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2019ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2019ActionPerformed

    private void txtd_2020ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2020ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2020ActionPerformed

    private void txtd_2021ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2021ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2021ActionPerformed

    private void txtd_2022ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2022ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2022ActionPerformed

    private void txtd_2023ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtd_2023ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtd_2023ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        d_2014 ss = new d_2014();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        d_2014 ss = new d_2014();
        ss.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        d_2015 ss = new d_2015();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        d_2015 ss = new d_2015();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        d_2016 ss = new d_2016();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        d_2016 ss = new d_2016();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        d_2017 ss = new d_2017();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        d_2017 ss = new d_2017();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        d_2018 ss = new d_2018();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        d_2018 ss = new d_2018();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        d_2019 ss = new d_2019();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        d_2019 ss = new d_2019();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        d_2020 ss = new d_2020();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        d_2020 ss = new d_2020();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        d_2021 ss = new d_2021();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        d_2021 ss = new d_2021();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        d_2022 ss = new d_2022();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        d_2022 ss = new d_2022();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        d_2023 ss = new d_2023();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        d_2023 ss = new d_2023();
        ss.setVisible(true);
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(d_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(d_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(d_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(d_general.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new d_general().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DTech;
    private javax.swing.JMenuItem MILimpiar;
    private javax.swing.JMenuItem MIMostrar;
    private javax.swing.JMenuItem MINuevoprincipal;
    private javax.swing.JMenuItem MIRegresar;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenuItem MenuItemEliminar;
    private javax.swing.JMenuItem MenuItemModificar;
    private javax.swing.JMenuItem MenuSalirDispose;
    private javax.swing.JMenuItem MenuSalirExit;
    private javax.swing.JPopupMenu PopupMenu;
    public static javax.swing.JTable Tablageneral;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JButton txtActualizar;
    private javax.swing.JTextField txtBuscar;
    public LIB.JTexfieldPH_FielTex txtNMedidor;
    public LIB.JTexfieldPH_FielTex txtNRegistro;
    public LIB.JTexfieldPH_FielTex txtayn;
    public LIB.JTexfieldPH_FielTex txtd_2014;
    public LIB.JTexfieldPH_FielTex txtd_2015;
    public LIB.JTexfieldPH_FielTex txtd_2016;
    public LIB.JTexfieldPH_FielTex txtd_2017;
    public LIB.JTexfieldPH_FielTex txtd_2018;
    public LIB.JTexfieldPH_FielTex txtd_2019;
    public LIB.JTexfieldPH_FielTex txtd_2020;
    public LIB.JTexfieldPH_FielTex txtd_2021;
    public LIB.JTexfieldPH_FielTex txtd_2022;
    public LIB.JTexfieldPH_FielTex txtd_2023;
    public LIB.JTexfieldPH_FielTex txtdireccion;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables


private static class datos {
    
        public datos() {
        }
    }


private void Limpiar(){

txtNRegistro.setText("");
txtNMedidor.setText("");
    txtayn.setText("");
    txtdireccion.setText("");
    
    txtd_2014.setText("");
    txtd_2015.setText("");
    txtd_2016.setText("");
    txtd_2017.setText("");
    txtd_2018.setText("");
    txtd_2019.setText("");
    txtd_2020.setText("");
    txtd_2021.setText("");
    txtd_2022.setText("");
    txtd_2023.setText("");
   
}






}
