
package Vistas;

import Conexion.conectar;
import FiveCodMover.FiveCodMoverJFrame;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.math.BigDecimal;
import javax.swing.*;
import java.net.URI;
import java.util.prefs.Preferences;
import javax.swing.table.DefaultTableCellRenderer;
import java.awt.Image;
import java.awt.Toolkit;


public class d_2016 extends javax.swing.JFrame {

  
    
    
    
    public d_2016() {
        initComponents();
        setIconImage(getIconImage());
        mostrardatos("");
        Limpiar();
        centrar_datos();
        setLocationRelativeTo(null);
       
        
    }
    
    
  //validar para que no acepte duplicados
    public void EvitarDuplicado(){
                
                
                DefaultTableModel modelo=new DefaultTableModel(){
            
            
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                if(columnas>=0)
                {
                    return false;
                    
                }else{
                    return true;
                }
                  
            }
    
    
    
    };
            
                for (int i = 0; i < Tabla2016.getRowCount() ; i++) { //recorrido por todas las filas de la tabla
                    if(Tabla2016.getValueAt(i, 0).equals(txtid2016.getText())) // verificar si el producto esta registrado
                    {
                    JOptionPane.showMessageDialog(null, "Ya existe alguien con este numero de registro");
                    modelo.removeRow(i); //eliminar la fila que se va a repetir
                    
                    }   
                        
                }
            
            
            }
       

    
  public void centrar_datos(){ //metodo centrar alineación centrada en celdas
  
DefaultTableCellRenderer tcr = new DefaultTableCellRenderer();
tcr.setHorizontalAlignment(SwingConstants.CENTER);



Tabla2016.getColumnModel().getColumn(0).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(1).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(3).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(4).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(5).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(6).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(7).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(8).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(9).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(10).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(11).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(12).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(13).setCellRenderer(tcr);
Tabla2016.getColumnModel().getColumn(14).setCellRenderer(tcr);
 
  }          
            

  
 @Override
    public Image getIconImage() {    
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Img/I7C.png"));
    return retValue;
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    
    
    
    public void mostrardatos(String valor){
        
        conectar cc=new conectar();
        Connection cn=cc.conexion();
        
        
        

        DefaultTableModel modelo=new DefaultTableModel(){
           
            
            @Override
            public boolean isCellEditable(int filas, int columnas) {
                if(columnas>=0)
                {
                    return false;
                    
                }else{
                    return true;
                }
                  
            }
    
             
    
    };
       
        
        
        modelo.addColumn("Numero de registro");
        modelo.addColumn("Numero de medidor");
        modelo.addColumn("Apellidos y Nombres");
        modelo.addColumn("Enero");
        modelo.addColumn("Febrero");
        modelo.addColumn("Marzo");
        modelo.addColumn("Abril");
        modelo.addColumn("Mayo");
        modelo.addColumn("Junio");
        modelo.addColumn("Julio");
        modelo.addColumn("Agosto");
        modelo.addColumn("Septiembre");
        modelo.addColumn("Octubre");
        modelo.addColumn("Noviembre");
        modelo.addColumn("Diciembre");
        
        
        
        Tabla2016.setModel(modelo); 
            
     
     
    Tabla2016.getColumnModel().getColumn(0).setPreferredWidth(120); 
    Tabla2016.getColumnModel().getColumn(0).setMinWidth(120); 
    Tabla2016.getColumnModel().getColumn(0).setMaxWidth(120); 
    
    Tabla2016.getColumnModel().getColumn(1).setPreferredWidth(125);
    Tabla2016.getColumnModel().getColumn(1).setMinWidth(125); 
    Tabla2016.getColumnModel().getColumn(1).setMaxWidth(125); 
   
     Tabla2016.getColumnModel().getColumn(2).setPreferredWidth(250);
    Tabla2016.getColumnModel().getColumn(2).setMinWidth(250); 
    Tabla2016.getColumnModel().getColumn(2).setMaxWidth(250); 
    
    Tabla2016.getColumnModel().getColumn(3).setPreferredWidth(45);
    Tabla2016.getColumnModel().getColumn(3).setMinWidth(45); 
    Tabla2016.getColumnModel().getColumn(3).setMaxWidth(45); 
    
    Tabla2016.getColumnModel().getColumn(4).setPreferredWidth(54);
    Tabla2016.getColumnModel().getColumn(4).setMinWidth(54); 
    Tabla2016.getColumnModel().getColumn(4).setMaxWidth(54); 
    
    Tabla2016.getColumnModel().getColumn(5).setPreferredWidth(43);
    Tabla2016.getColumnModel().getColumn(5).setMinWidth(43); 
    Tabla2016.getColumnModel().getColumn(5).setMaxWidth(43); 
    
    Tabla2016.getColumnModel().getColumn(6).setPreferredWidth(36);
    Tabla2016.getColumnModel().getColumn(6).setMinWidth(36); 
    Tabla2016.getColumnModel().getColumn(6).setMaxWidth(36); 
    
    Tabla2016.getColumnModel().getColumn(7).setPreferredWidth(39);
    Tabla2016.getColumnModel().getColumn(7).setMinWidth(39); 
    Tabla2016.getColumnModel().getColumn(7).setMaxWidth(39);
   
    Tabla2016.getColumnModel().getColumn(8).setPreferredWidth(43);
    Tabla2016.getColumnModel().getColumn(8).setMinWidth(43); 
    Tabla2016.getColumnModel().getColumn(8).setMaxWidth(43);
        
    Tabla2016.getColumnModel().getColumn(9).setPreferredWidth(39);
    Tabla2016.getColumnModel().getColumn(9).setMinWidth(39); 
    Tabla2016.getColumnModel().getColumn(9).setMaxWidth(39);
    
    Tabla2016.getColumnModel().getColumn(10).setPreferredWidth(49);
    Tabla2016.getColumnModel().getColumn(10).setMinWidth(49); 
    Tabla2016.getColumnModel().getColumn(10).setMaxWidth(49);
    
    Tabla2016.getColumnModel().getColumn(10).setPreferredWidth(55);
    Tabla2016.getColumnModel().getColumn(10).setMinWidth(55); 
    Tabla2016.getColumnModel().getColumn(10).setMaxWidth(55);
    
    Tabla2016.getColumnModel().getColumn(11).setPreferredWidth(75);
    Tabla2016.getColumnModel().getColumn(11).setMinWidth(75); 
    Tabla2016.getColumnModel().getColumn(11).setMaxWidth(75);
    
    Tabla2016.getColumnModel().getColumn(12).setPreferredWidth(54);
    Tabla2016.getColumnModel().getColumn(12).setMinWidth(54); 
    Tabla2016.getColumnModel().getColumn(12).setMaxWidth(54);
    
    Tabla2016.getColumnModel().getColumn(13).setPreferredWidth(71);
    Tabla2016.getColumnModel().getColumn(13).setMinWidth(71); 
    Tabla2016.getColumnModel().getColumn(13).setMaxWidth(71);
    
    Tabla2016.getColumnModel().getColumn(14).setPreferredWidth(71);
    Tabla2016.getColumnModel().getColumn(14).setMinWidth(71); 
    Tabla2016.getColumnModel().getColumn(14).setMaxWidth(71);
        
        
        
        
        String sql="";
        
        if (valor.equals(""))
        {
            sql="SELECT * FROM deudas2016";
        }
        else{
            sql="SELECT * FROM deudas2016 WHERE id_deuda2016 LIKE '%"+valor+"%' OR n_medidor LIKE '%"+valor+"%' OR ayn LIKE '%"+valor+"%' OR enero LIKE '%"+valor+"%' OR febrero LIKE '%"+valor+"%' OR marzo LIKE '%"+valor+"%' OR abril LIKE '%"+valor+"%' OR mayo LIKE '%"+valor+"%' OR junio LIKE '%"+valor+"%' OR julio LIKE '%"+valor+"%' OR agosto LIKE '%"+valor+"%' OR septiembre LIKE '%"+valor+"%' OR octubre LIKE '%"+valor+"%' OR noviembre LIKE '%"+valor+"%' OR diciembre LIKE '%"+valor+"%'";
        }  
        
        
        
        
        String []datos=new String [15];
        try{
            Statement st=cn.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
            datos[0]=rs.getString(1);
            datos[1]=rs.getString(2);
            datos[2]=rs.getString(3);
            
            datos[3]=rs.getString(4);
            datos[4]=rs.getString(5);
            datos[5]=rs.getString(6);
            datos[6]=rs.getString(7);
            datos[7]=rs.getString(8);
            datos[8]=rs.getString(9);
            datos[9]=rs.getString(10);
            datos[10]=rs.getString(11);
            datos[11]=rs.getString(12);
            datos[12]=rs.getString(13);
            datos[13]=rs.getString(14);
            datos[14]=rs.getString(15);
           
            modelo.addRow(datos);
            
            }
           
                     
//            TablaGeneral.setModel(modelo);
        }catch(SQLException ex){
            Logger.getLogger(d_2016.datos.class.getName()).log(Level.SEVERE,null,ex);
        }
        
       
        
        
        
        
    }
    
   
        
    
    
    
    
    
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupMenu = new javax.swing.JPopupMenu();
        MenuItemModificar = new javax.swing.JMenuItem();
        MenuItemEliminar = new javax.swing.JMenuItem();
        panel = new javax.swing.JPanel();
        txtNMedidor = new LIB.JTexfieldPH_FielTex();
        txtid2016 = new LIB.JTexfieldPH_FielTex();
        txtayn = new LIB.JTexfieldPH_FielTex();
        txtenero = new LIB.JTexfieldPH_FielTex();
        txtfebrero = new LIB.JTexfieldPH_FielTex();
        txtmarzo = new LIB.JTexfieldPH_FielTex();
        txtabril = new LIB.JTexfieldPH_FielTex();
        txtmayo = new LIB.JTexfieldPH_FielTex();
        txtjunio = new LIB.JTexfieldPH_FielTex();
        txtjulio = new LIB.JTexfieldPH_FielTex();
        txtagosto = new LIB.JTexfieldPH_FielTex();
        txtseptiembre = new LIB.JTexfieldPH_FielTex();
        txtoctubre = new LIB.JTexfieldPH_FielTex();
        txtnoviembre = new LIB.JTexfieldPH_FielTex();
        txtdiciembre = new LIB.JTexfieldPH_FielTex();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla2016 = new javax.swing.JTable();
        DTech = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtActualizar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        txtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuArchivo = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        MenuSalirDispose = new javax.swing.JMenuItem();
        MenuSalirExit = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu14 = new javax.swing.JMenu();
        jMenu15 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenu16 = new javax.swing.JMenu();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenu17 = new javax.swing.JMenu();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenu18 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu19 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenu20 = new javax.swing.JMenu();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu21 = new javax.swing.JMenu();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu22 = new javax.swing.JMenu();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenuItem37 = new javax.swing.JMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenuItem38 = new javax.swing.JMenuItem();
        jMenuItem39 = new javax.swing.JMenuItem();
        jMenu24 = new javax.swing.JMenu();
        jMenuItem40 = new javax.swing.JMenuItem();
        jMenuItem41 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MILimpiar = new javax.swing.JMenuItem();
        MIMostrar = new javax.swing.JMenuItem();
        MIRegresar = new javax.swing.JMenuItem();
        MINuevoprincipal = new javax.swing.JMenuItem();

        MenuItemModificar.setText("Modificar");
        MenuItemModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemModificarActionPerformed(evt);
            }
        });
        PopupMenu.add(MenuItemModificar);

        MenuItemEliminar.setText("Eliminar");
        MenuItemEliminar.setComponentPopupMenu(PopupMenu);
        MenuItemEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemEliminarActionPerformed(evt);
            }
        });
        PopupMenu.add(MenuItemEliminar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        panel.setBackground(new java.awt.Color(255, 255, 255));

        txtNMedidor.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtNMedidor.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtNMedidor.setOpaque(false);
        txtNMedidor.setPlaceholder("Nro de medidor");
        txtNMedidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNMedidorActionPerformed(evt);
            }
        });

        txtid2016.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtid2016.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtid2016.setOpaque(false);
        txtid2016.setPlaceholder("Nro de registro");
        txtid2016.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtid2016ActionPerformed(evt);
            }
        });

        txtayn.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtayn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtayn.setOpaque(false);
        txtayn.setPlaceholder("Apellidos y Nombres");
        txtayn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaynActionPerformed(evt);
            }
        });

        txtenero.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtenero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtenero.setOpaque(false);
        txtenero.setPlaceholder("Enero");
        txtenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txteneroActionPerformed(evt);
            }
        });

        txtfebrero.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtfebrero.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtfebrero.setOpaque(false);
        txtfebrero.setPlaceholder("Febrero");
        txtfebrero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfebreroActionPerformed(evt);
            }
        });

        txtmarzo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtmarzo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtmarzo.setOpaque(false);
        txtmarzo.setPlaceholder("Marzo");
        txtmarzo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmarzoActionPerformed(evt);
            }
        });

        txtabril.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtabril.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtabril.setOpaque(false);
        txtabril.setPlaceholder("Abril");
        txtabril.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtabrilActionPerformed(evt);
            }
        });

        txtmayo.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtmayo.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtmayo.setOpaque(false);
        txtmayo.setPlaceholder("Mayo");
        txtmayo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmayoActionPerformed(evt);
            }
        });

        txtjunio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtjunio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtjunio.setOpaque(false);
        txtjunio.setPlaceholder("Junio");
        txtjunio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjunioActionPerformed(evt);
            }
        });

        txtjulio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtjulio.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtjulio.setOpaque(false);
        txtjulio.setPlaceholder("Julio");
        txtjulio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjulioActionPerformed(evt);
            }
        });

        txtagosto.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtagosto.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtagosto.setOpaque(false);
        txtagosto.setPlaceholder("Agosto");
        txtagosto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtagostoActionPerformed(evt);
            }
        });

        txtseptiembre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtseptiembre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtseptiembre.setOpaque(false);
        txtseptiembre.setPlaceholder("Septiembre");
        txtseptiembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtseptiembreActionPerformed(evt);
            }
        });

        txtoctubre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtoctubre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtoctubre.setOpaque(false);
        txtoctubre.setPlaceholder("Octubre");
        txtoctubre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtoctubreActionPerformed(evt);
            }
        });

        txtnoviembre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtnoviembre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtnoviembre.setOpaque(false);
        txtnoviembre.setPlaceholder("Noviembre");
        txtnoviembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnoviembreActionPerformed(evt);
            }
        });

        txtdiciembre.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtdiciembre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        txtdiciembre.setOpaque(false);
        txtdiciembre.setPlaceholder("Diciembre");
        txtdiciembre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtdiciembreActionPerformed(evt);
            }
        });

        Tabla2016.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Tabla2016.setComponentPopupMenu(PopupMenu);
        jScrollPane1.setViewportView(Tabla2016);

        DTech.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/DTECHINNOVA1.3.png"))); // NOI18N
        DTech.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DTech.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DTechMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/CREADOPOR1.png"))); // NOI18N

        btnBuscar.setBackground(new java.awt.Color(10, 144, 203));
        btnBuscar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setMaximumSize(new java.awt.Dimension(103, 31));
        btnBuscar.setMinimumSize(new java.awt.Dimension(103, 31));
        btnBuscar.setPreferredSize(new java.awt.Dimension(103, 31));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtActualizar.setBackground(new java.awt.Color(10, 144, 203));
        txtActualizar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        txtActualizar.setForeground(new java.awt.Color(255, 255, 255));
        txtActualizar.setText("Validar datos");
        txtActualizar.setMaximumSize(new java.awt.Dimension(103, 31));
        txtActualizar.setMinimumSize(new java.awt.Dimension(103, 31));
        txtActualizar.setPreferredSize(new java.awt.Dimension(103, 31));
        txtActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActualizarActionPerformed(evt);
            }
        });

        btnAgregar.setBackground(new java.awt.Color(10, 144, 203));
        btnAgregar.setFont(new java.awt.Font("Segoe UI Semibold", 0, 16)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar registro");
        btnAgregar.setMaximumSize(new java.awt.Dimension(103, 31));
        btnAgregar.setMinimumSize(new java.awt.Dimension(103, 31));
        btnAgregar.setPreferredSize(new java.awt.Dimension(103, 31));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        txtBuscar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 36)); // NOI18N
        jLabel1.setText("2016");

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtid2016, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtayn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtjulio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtoctubre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(txtagosto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txtnoviembre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(txtdiciembre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(txtseptiembre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(txtabril, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtmayo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtjunio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(panelLayout.createSequentialGroup()
                                                .addComponent(txtenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtfebrero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtmarzo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(268, 268, 268)))
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DTech))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelLayout.createSequentialGroup()
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 793, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(25, 25, 25))))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DTech)
                            .addComponent(jLabel2))
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtenero, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmarzo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtfebrero, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtabril, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtmayo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtjunio, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtjulio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtagosto, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtseptiembre, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addComponent(txtid2016, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNMedidor, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtayn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtoctubre, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnoviembre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiciembre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)))
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        MenuArchivo.setText("Archivo");
        MenuArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuArchivoActionPerformed(evt);
            }
        });

        jMenu1.setText("Salir");

        MenuSalirDispose.setText("Salir de esta ventana");
        MenuSalirDispose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirDisposeActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSalirDispose);

        MenuSalirExit.setText("Salir del programa");
        MenuSalirExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirExitActionPerformed(evt);
            }
        });
        jMenu1.add(MenuSalirExit);

        MenuArchivo.add(jMenu1);

        jMenuItem19.setText("Actualizar Ventana");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        MenuArchivo.add(jMenuItem19);

        jMenuBar1.add(MenuArchivo);

        jMenu14.setText("Deudas");

        jMenu15.setText("2014");

        jMenuItem22.setText("Abrir");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem22);

        jMenuItem23.setText("Abrir en una nueva ventana");
        jMenuItem23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem23ActionPerformed(evt);
            }
        });
        jMenu15.add(jMenuItem23);

        jMenu14.add(jMenu15);

        jMenu16.setText("2015");

        jMenuItem24.setText("Abrir");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem24);

        jMenuItem25.setText("Abrir en una nueva ventana");
        jMenuItem25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem25ActionPerformed(evt);
            }
        });
        jMenu16.add(jMenuItem25);

        jMenu14.add(jMenu16);

        jMenu17.setText("2016");

        jMenuItem26.setText("Abrir");
        jMenuItem26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem26ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem26);

        jMenuItem27.setText("Abrir en una nueva ventana");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu17.add(jMenuItem27);

        jMenu14.add(jMenu17);

        jMenu18.setText("2017");

        jMenuItem28.setText("Abrir");
        jMenuItem28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem28ActionPerformed(evt);
            }
        });
        jMenu18.add(jMenuItem28);

        jMenuItem29.setText("Abrir en una nueva ventana");
        jMenuItem29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem29ActionPerformed(evt);
            }
        });
        jMenu18.add(jMenuItem29);

        jMenu14.add(jMenu18);

        jMenu19.setText("2018");

        jMenuItem30.setText("Abrir");
        jMenuItem30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem30ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem30);

        jMenuItem31.setText("Abrir en una nueva ventana");
        jMenuItem31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem31ActionPerformed(evt);
            }
        });
        jMenu19.add(jMenuItem31);

        jMenu14.add(jMenu19);

        jMenu20.setText("2019");

        jMenuItem32.setText("Abrir");
        jMenuItem32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem32ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem32);

        jMenuItem33.setText("Abrir en una nueva ventana");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        jMenu20.add(jMenuItem33);

        jMenu14.add(jMenu20);

        jMenu21.setText("2020");

        jMenuItem34.setText("Abrir");
        jMenuItem34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem34ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem34);

        jMenuItem35.setText("Abrir en una nueva ventana");
        jMenuItem35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem35ActionPerformed(evt);
            }
        });
        jMenu21.add(jMenuItem35);

        jMenu14.add(jMenu21);

        jMenu22.setText("2021");

        jMenuItem36.setText("Abrir");
        jMenuItem36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem36ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem36);

        jMenuItem37.setText("Abrir en una nueva ventana");
        jMenuItem37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem37ActionPerformed(evt);
            }
        });
        jMenu22.add(jMenuItem37);

        jMenu14.add(jMenu22);

        jMenu23.setText("2022");

        jMenuItem38.setText("Abrir");
        jMenuItem38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem38ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem38);

        jMenuItem39.setText("Abrir en una nueva ventana");
        jMenuItem39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem39ActionPerformed(evt);
            }
        });
        jMenu23.add(jMenuItem39);

        jMenu14.add(jMenu23);

        jMenu24.setText("2023");

        jMenuItem40.setText("Abrir");
        jMenuItem40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem40ActionPerformed(evt);
            }
        });
        jMenu24.add(jMenuItem40);

        jMenuItem41.setText("Abrir en una nueva ventana");
        jMenuItem41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem41ActionPerformed(evt);
            }
        });
        jMenu24.add(jMenuItem41);

        jMenu14.add(jMenu24);

        jMenuBar1.add(jMenu14);

        jMenu2.setText("Opciones");

        MILimpiar.setText("Limpiar celdas");
        MILimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MILimpiarActionPerformed(evt);
            }
        });
        jMenu2.add(MILimpiar);

        MIMostrar.setText("Mostrar todos los registros");
        MIMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIMostrarActionPerformed(evt);
            }
        });
        jMenu2.add(MIMostrar);

        MIRegresar.setText("Regresar a la ventana principal");
        MIRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MIRegresarActionPerformed(evt);
            }
        });
        jMenu2.add(MIRegresar);

        MINuevoprincipal.setText("Abrir la ventana principal en una nueva ventana");
        MINuevoprincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MINuevoprincipalActionPerformed(evt);
            }
        });
        jMenu2.add(MINuevoprincipal);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
 
    String id_deuda2016= "";
    private void MenuItemModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemModificarActionPerformed
       
        
    int fila=Tabla2016.getSelectedRow();
    
    if(fila>=0){
        
    txtid2016.setText(Tabla2016.getValueAt(fila,0).toString());
    txtNMedidor.setText(Tabla2016.getValueAt(fila,1).toString());
    txtayn.setText(Tabla2016.getValueAt(fila,2).toString());
    
    txtenero.setText(Tabla2016.getValueAt(fila,3).toString());
    txtfebrero.setText(Tabla2016.getValueAt(fila,4).toString());
    txtmarzo.setText(Tabla2016.getValueAt(fila,5).toString());
    txtabril.setText(Tabla2016.getValueAt(fila,6).toString());
    txtmayo.setText(Tabla2016.getValueAt(fila,7).toString());
    txtjunio.setText(Tabla2016.getValueAt(fila,8).toString());
    txtjulio.setText(Tabla2016.getValueAt(fila,9).toString());
    txtagosto.setText(Tabla2016.getValueAt(fila,10).toString());
    txtseptiembre.setText(Tabla2016.getValueAt(fila,11).toString());
    txtoctubre.setText(Tabla2016.getValueAt(fila,12).toString());
    txtnoviembre.setText(Tabla2016.getValueAt(fila,13).toString());
    txtdiciembre.setText(Tabla2016.getValueAt(fila,14).toString());
    

    }
    else{
        JOptionPane.showMessageDialog(null,"No se encontro fila");
    }
     
        
        
        
        
    }//GEN-LAST:event_MenuItemModificarActionPerformed

    private void MILimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MILimpiarActionPerformed
        Limpiar();
    }//GEN-LAST:event_MILimpiarActionPerformed

    private void MIMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIMostrarActionPerformed
       mostrardatos("");
       centrar_datos();
    }//GEN-LAST:event_MIMostrarActionPerformed

    private void MIRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MIRegresarActionPerformed
      d_general ss = new d_general();
        ss.setVisible(true);
        this.dispose();    
    }//GEN-LAST:event_MIRegresarActionPerformed

    private void MINuevoprincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MINuevoprincipalActionPerformed
         d_general ss = new d_general();
         ss.setVisible(true);           
    }//GEN-LAST:event_MINuevoprincipalActionPerformed

    private void MenuArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuArchivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuArchivoActionPerformed

    private void MenuSalirDisposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirDisposeActionPerformed
        dispose(); 
    }//GEN-LAST:event_MenuSalirDisposeActionPerformed

    private void MenuSalirExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSalirExitActionPerformed

    private void MenuItemEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemEliminarActionPerformed
        
        
int q1 = JOptionPane.showConfirmDialog(null, "¿Esta seguro de eliminar este registro?","Mensaje",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
if (q1 == 0){
conectar cc=new conectar();
        Connection cn=cc.conexion();
        int fila=Tabla2016.getSelectedRow();
        String cod="";
        cod=Tabla2016.getValueAt(fila,0).toString();
        try{
            PreparedStatement pst=cn.prepareStatement("DELETE FROM deudas2016 WHERE id_deuda2016='"+cod+"'");
            pst.executeUpdate();
            mostrardatos("");
            centrar_datos();
        } catch (Exception e){
        }  
}
if (q1 == 1){

}

        
        
        
        
        
        
        
    }//GEN-LAST:event_MenuItemEliminarActionPerformed

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed

    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        conectar cc=new conectar();
        Connection cn=cc.conexion();
        EvitarDuplicado();
        try{
            PreparedStatement pst=cn.prepareStatement("INSERT INTO deudas2016 (id_deuda2016,n_medidor,ayn,enero,febrero,marzo,abril,mayo,junio,julio,agosto,septiembre,octubre,noviembre,diciembre) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");
            pst.setString(1,txtid2016.getText());
            pst.setString(2,txtNMedidor.getText());
            pst.setString(3,txtayn.getText());
            pst.setString(4,txtenero.getText());
            pst.setString(5,txtfebrero.getText());
            pst.setString(6,txtmarzo.getText());
            pst.setString(7,txtabril.getText());
            pst.setString(8,txtmayo.getText());
            pst.setString(9,txtjunio.getText());
            pst.setString(10,txtjulio.getText());
            pst.setString(11,txtagosto.getText());
            pst.setString(12,txtseptiembre.getText());
            pst.setString(13,txtoctubre.getText());
            pst.setString(14,txtnoviembre.getText());
            pst.setString(15,txtdiciembre.getText());

            int a=pst.executeUpdate();

            if(a>0){
                JOptionPane.showMessageDialog(null,"Registro exitoso");
                mostrardatos("");
                centrar_datos();
            }
            else{
                JOptionPane.showMessageDialog(null,"Error al agregar");
            }
        }catch(Exception e){
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActualizarActionPerformed

        conectar cc=new conectar();
        Connection cn=cc.conexion();

        try{

            PreparedStatement pst=cn.prepareStatement("UPDATE deudas2016 SET diciembre='"+txtdiciembre.getText()+"',noviembre='"+txtnoviembre.getText()+"',octubre='"+txtoctubre.getText()+"',septiembre='"+txtseptiembre.getText()+"',agosto='"+txtagosto.getText()+"',julio='"+txtjulio.getText()+"',junio='"+txtjunio.getText()+"',mayo='"+txtmayo.getText()+"',abril='"+txtabril.getText()+"',marzo='"+txtmarzo.getText()+"',febrero='"+txtfebrero.getText()+"',enero='"+txtenero.getText()+"',ayn='"+txtayn.getText()+"',n_medidor='"+txtNMedidor.getText()+"',id_deuda2016 ='"+txtid2016.getText()+"' WHERE id_deuda2016='"+id_deuda2016+"' ");
            id_deuda2016=txtid2016.getText();
            pst.executeUpdate();
            mostrardatos("");
            centrar_datos();
            JOptionPane.showMessageDialog(null, "datos validados");
        }catch(Exception e){
            System.out.print(e.getMessage());
        }
    }//GEN-LAST:event_txtActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        mostrardatos(txtBuscar.getText());
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void DTechMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DTechMouseClicked
        try {
            if(Desktop.isDesktopSupported()){
                Desktop desktop = Desktop.getDesktop();
                if(desktop.isSupported(Desktop.Action.BROWSE)){

                    desktop.browse(new URI ("https://wa.me/+51928583538?text=Hola.%20Necesito%20de%20su%20servicio."));

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_DTechMouseClicked

    private void txtdiciembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtdiciembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtdiciembreActionPerformed

    private void txtnoviembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnoviembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnoviembreActionPerformed

    private void txtoctubreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtoctubreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtoctubreActionPerformed

    private void txtseptiembreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtseptiembreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtseptiembreActionPerformed

    private void txtagostoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtagostoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtagostoActionPerformed

    private void txtjulioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjulioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjulioActionPerformed

    private void txtjunioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjunioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjunioActionPerformed

    private void txtmayoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmayoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmayoActionPerformed

    private void txtabrilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtabrilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtabrilActionPerformed

    private void txtmarzoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmarzoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtmarzoActionPerformed

    private void txtfebreroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfebreroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfebreroActionPerformed

    private void txteneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txteneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txteneroActionPerformed

    private void txtaynActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaynActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtaynActionPerformed

    private void txtid2016ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtid2016ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtid2016ActionPerformed

    private void txtNMedidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNMedidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNMedidorActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        mostrardatos("");
        centrar_datos();
        JOptionPane.showMessageDialog(null,"La ventana fue actualizada","Mensaje", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        d_2014 ss = new d_2014();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem23ActionPerformed
        d_2014 ss = new d_2014();
        ss.setVisible(true);
    }//GEN-LAST:event_jMenuItem23ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        d_2015 ss = new d_2015();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem25ActionPerformed
        d_2015 ss = new d_2015();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem25ActionPerformed

    private void jMenuItem26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem26ActionPerformed
        d_2016 ss = new d_2016();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem26ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        d_2016 ss = new d_2016();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem28ActionPerformed
        d_2017 ss = new d_2017();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem28ActionPerformed

    private void jMenuItem29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem29ActionPerformed
        d_2017 ss = new d_2017();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem29ActionPerformed

    private void jMenuItem30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem30ActionPerformed
        d_2018 ss = new d_2018();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem30ActionPerformed

    private void jMenuItem31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem31ActionPerformed
        d_2018 ss = new d_2018();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem31ActionPerformed

    private void jMenuItem32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem32ActionPerformed
        d_2019 ss = new d_2019();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem32ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        d_2019 ss = new d_2019();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem33ActionPerformed

    private void jMenuItem34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem34ActionPerformed
        d_2020 ss = new d_2020();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem34ActionPerformed

    private void jMenuItem35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem35ActionPerformed
        d_2020 ss = new d_2020();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem35ActionPerformed

    private void jMenuItem36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem36ActionPerformed
        d_2021 ss = new d_2021();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem36ActionPerformed

    private void jMenuItem37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem37ActionPerformed
        d_2021 ss = new d_2021();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem37ActionPerformed

    private void jMenuItem38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem38ActionPerformed
        d_2022 ss = new d_2022();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem38ActionPerformed

    private void jMenuItem39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem39ActionPerformed
        d_2022 ss = new d_2022();
        ss.setVisible(true);

    }//GEN-LAST:event_jMenuItem39ActionPerformed

    private void jMenuItem40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem40ActionPerformed
        d_2023 ss = new d_2023();
        ss.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jMenuItem40ActionPerformed

    private void jMenuItem41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem41ActionPerformed
        d_2023 ss = new d_2023();
        ss.setVisible(true);
    }//GEN-LAST:event_jMenuItem41ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(d_2016.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(d_2016.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(d_2016.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(d_2016.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new d_2016().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DTech;
    private javax.swing.JMenuItem MILimpiar;
    private javax.swing.JMenuItem MIMostrar;
    private javax.swing.JMenuItem MINuevoprincipal;
    private javax.swing.JMenuItem MIRegresar;
    private javax.swing.JMenu MenuArchivo;
    private javax.swing.JMenuItem MenuItemEliminar;
    private javax.swing.JMenuItem MenuItemModificar;
    private javax.swing.JMenuItem MenuSalirDispose;
    private javax.swing.JMenuItem MenuSalirExit;
    private javax.swing.JPopupMenu PopupMenu;
    public static javax.swing.JTable Tabla2016;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu14;
    private javax.swing.JMenu jMenu15;
    private javax.swing.JMenu jMenu16;
    private javax.swing.JMenu jMenu17;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu20;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenu jMenu24;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem37;
    private javax.swing.JMenuItem jMenuItem38;
    private javax.swing.JMenuItem jMenuItem39;
    private javax.swing.JMenuItem jMenuItem40;
    private javax.swing.JMenuItem jMenuItem41;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JButton txtActualizar;
    private javax.swing.JTextField txtBuscar;
    public LIB.JTexfieldPH_FielTex txtNMedidor;
    public LIB.JTexfieldPH_FielTex txtabril;
    public LIB.JTexfieldPH_FielTex txtagosto;
    public LIB.JTexfieldPH_FielTex txtayn;
    public LIB.JTexfieldPH_FielTex txtdiciembre;
    public LIB.JTexfieldPH_FielTex txtenero;
    public LIB.JTexfieldPH_FielTex txtfebrero;
    public LIB.JTexfieldPH_FielTex txtid2016;
    public LIB.JTexfieldPH_FielTex txtjulio;
    public LIB.JTexfieldPH_FielTex txtjunio;
    public LIB.JTexfieldPH_FielTex txtmarzo;
    public LIB.JTexfieldPH_FielTex txtmayo;
    public LIB.JTexfieldPH_FielTex txtnoviembre;
    public LIB.JTexfieldPH_FielTex txtoctubre;
    public LIB.JTexfieldPH_FielTex txtseptiembre;
    // End of variables declaration//GEN-END:variables


private static class datos {
    
        public datos() {
        }
    }


private void Limpiar(){

txtid2016.setText("");
txtNMedidor.setText("");
    txtayn.setText("");
    
    txtenero.setText("");
    txtfebrero.setText("");
    txtmarzo.setText("");
    txtabril.setText("");
    txtmayo.setText("");
    txtjunio.setText("");
    txtjulio.setText("");
    txtagosto.setText("");
    txtseptiembre.setText("");
    txtoctubre.setText("");
    txtnoviembre.setText("");
    txtdiciembre.setText("");
}






}
